# Generated by Django 4.2.4 on 2023-08-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adotar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_adocao',
            name='dono_pet',
            field=models.CharField(default='admin', max_length=120),
        ),
    ]
