# Generated by Django 4.2.4 on 2023-08-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adotar', '0002_pedido_adocao_dono_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_adocao',
            name='email_adotante',
            field=models.CharField(default='sememail@gmail.com', max_length=200),
        ),
    ]
